export const cards = [
  {
    id: 1,
    title: "AC Technicians",
    desc: "Repair your AC in no time",
    img: "",
    slug: "ac-technicians",
  },
  {
    id: 2,
    title: "Electricians",
    desc: "Fix electrical issues efficiently",
    img: "",
    slug: "electricians",
  },
  {
    id: 3,
    title: "Plumbers",
    desc: "Solve plumbing problems quickly",
    img: "",
    slug: "plumbers",
  },
  {
    id: 4,
    title: "Mechanics",
    desc: "Expert car and bike repair services",
    img: "",
    slug: "mechanics",
  },
  {
    id: 5,
    title: "Carpenters",
    desc: "Furniture repair and custom woodwork",
    img: "",
    slug: "carpenters",
  },
  {
    id: 6,
    title: "Technicians",
    desc: "Professional technical services",
    img: "",
    slug: "technicians",
  },
  {
    id: 7,
    title: "Cleaning and Pest Control",
    desc: "Keep your space clean and pest-free",
    img: "",
    slug: "cleaning-and-pest-control",
  },
  {
    id: 8,
    title: "Home Appliances Repair",
    desc: "Fix and maintain home appliances",
    img: "",
    slug: "home-appliances-repair",
  },
  {
    id: 9,
    title: "Building Paintings",
    desc: "Quality painting for your home or office",
    img: "",
    slug: "building-paintings",
  },
];


export const projects = [
  {
    id: 1,
    img: "https://s3-alpha.figma.com/hub/file/808763618/bdb37100-4cd9-4d05-88a5-6c21dc056fac-cover.png",
    pp: "https://images.pexels.com/photos/2603464/pexels-photo-2603464.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Web and Mobile Design",
    username: "Aridaman Singh",
  },
  {
    id: 2,
    img: "https://img.freepik.com/free-vector/golden-bird-logo-design_1195-336.jpg",
    pp: "https://c4.wallpaperflare.com/wallpaper/776/796/970/new-york-comics-spider-man-miles-morales-ultimate-spider-man-hd-wallpaper-preview.jpg",
    cat: "Logo Design",
    username: "Ankush",
  },
  {
    id: 3,
    img: "https://images.pexels.com/photos/590016/pexels-photo-590016.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1693095/pexels-photo-1693095.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    cat: "Data Entry",
    username: "Rahul Shrivastava",
  },
  {
    id: 4,
    img: "https://webdesignersbangalore.in/wp-content/uploads/2021/05/wd-bangalore-SEO.jpg",
    pp: "https://images.pexels.com/photos/1921336/pexels-photo-1921336.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "SEO",
    username: "Vishesh Agrawal",
  },
  {
    id: 5,
    img: "https://images.pexels.com/photos/2290786/pexels-photo-2290786.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/3354346/pexels-photo-3354346.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Social Media Design",
    username: "Shashwat Khare",
  },
  {
    id: 6,
    img: "https://images.pexels.com/photos/908713/pexels-photo-908713.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/163077/mario-yoschi-figures-funny-163077.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Illustration",
    username: "Abhishek Singh",
  },
  {
    id: 7,
    img: "https://www.shutterstock.com/blog/wp-content/uploads/sites/5/2022/09/handmade-photo-album.jpg?w=720",
    pp: "https://images.pexels.com/photos/2838511/pexels-photo-2838511.jpeg?auto=compress&cs=tinysrgb&w=1660",
    cat: "Book Design",
    username: "Aditya Ashish Parmar",
  },
  {
    id: 8,
    img: "https://www.lonefircreative.com/hubfs/blog%20images/lone-fir-creative-Which-Digital-Marketing-Services-Are-Right-For-You.jpg",
    pp: "https://images.pexels.com/photos/36717/amazing-animal-beautiful-beautifull.jpg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Digital Marketing",
    username: "Ankur Rai",
  },
];

export const gigs = [
  {
    id: 1,
    img: "https://images.pexels.com/photos/580151/pexels-photo-580151.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/720598/pexels-photo-720598.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create ai art character from your images and prompts",
    price: 59,
    star: 5,
    username: "Anna Bell",
  },
  {
    id: 2,
    img: "https://images.pexels.com/photos/4145190/pexels-photo-4145190.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1036627/pexels-photo-1036627.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create ultra high quality character art with ai",
    price: 79,
    star: 5,
    username: "Lannie Coleman",
  },
  {
    id: 3,
    img: "https://images.pexels.com/photos/8797307/pexels-photo-8797307.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1062280/pexels-photo-1062280.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will creating unique ai generated artworks mid journey ai artist",
    price: 112,
    star: 5,
    username: "Carol Steve",
  },
  {
    id: 4,
    img: "https://images.pexels.com/photos/5708069/pexels-photo-5708069.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create custom ai generated artwork using your photos",
    price: 99,
    star: 4,
    username: "Don Weber",
  },
  {
    id: 5,
    img: "https://images.pexels.com/photos/5699456/pexels-photo-5699456.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1771383/pexels-photo-1771383.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will recreate your dreams in high quality pictures",
    price: 59,
    star: 5,
    username: "Audrey Richards",
  },
  {
    id: 6,
    img: "https://images.pexels.com/photos/8100784/pexels-photo-8100784.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/715546/pexels-photo-715546.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create ai digital art illustration hyper realistic painting",
    price: 79,
    star: 4,
    username: "Walton Shepard ",
  },
  {
    id: 7,
    img: "https://images.pexels.com/photos/6039245/pexels-photo-6039245.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/720606/pexels-photo-720606.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will generate images with your prompts using ai dalle",
    price: 89,
    star: 5,
    username: "Waverly Schaefer",
  },
  {
    id: 8,
    img: "https://images.pexels.com/photos/5490778/pexels-photo-5490778.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1699159/pexels-photo-1699159.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create custom art using midjourney generator",
    price: 110,
    star: 4,
    username: "Wilton Hunt",
  },
];
